---
- name: 'Instala requerimentos da aplicação'
  apt:
    update_cache: yes
    name: ['python3', 'python-dev', 'python3-dev', 'python3-pip', 
           'python3-venv', 'build-essential', 'libssl-dev', 'libffi-dev',
           'libxml2-dev', 'libxslt1-dev', 'zlib1g-dev']
    state: latest
  become: yes